apiVersion: apps/v1
kind: Deployment
metadata:
  name: golang-api-deployment
  labels:
    app: golang-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: golang-api
  template:
    metadata:
      labels:
        app: golang-api
    spec:
      containers:
        - name: golang-api
          image: shivangshandilya/golang-api-{{IMAGE_TAG}}
          ports:
          - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
