apiVersion: v1
kind: Service
metadata:
  name: golang-api-service
spec:
  type: NodePort
  selector:
    app: go-rest-api
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      protocol: TCP
